Update code

diff --git a/libs/Makefile b/libs/Makefile
--- a/libs/Makefile
+++ b/libs/Makefile
@@ -5,10 +5,10 @@ LOC_DIR ?=$(CURDIR)/../local
 
 .PHONY: prerequisites
 .DEFAULT: prerequisites
-prerequisites: folders snap sdsl
+prerequisites: folders lemon sdsl #snap
 
 .PHONY: clean-prerequisites
-clean-prerequisites: clean-snap clean-sdsl
+clean-prerequisites: clean-lemon clean-sdsl #clean-snap
 
 .PHONY: folders
 folders:
@@ -16,7 +16,34 @@ folders:
 	[ -d $(LOC_DIR) ] || mkdir -p $(LOC_DIR) ; \
 	[ -d $(LOC_DIR)/include ] || mkdir -p $(LOC_DIR)/include ; \
 	[ -d $(LOC_DIR)/lib ] || mkdir -p $(LOC_DIR)/lib ; \
+	[ -d $(LOC_DIR)/lemon ] || mkdir -p $(LOC_DIR)/lemon ; \
 	[ -f $(LOC_DIR)/fasta.o ] || echo "* Fasta"
+
+.PHONY: lemon
+lemon: folders $(LOC_DIR)/lemon/include/
+
+LEMON_NAME:=lemon-1.3.1
+$(LOC_DIR)/lemon/include/:
+	@echo "* Lemon Library" ;	\
+	tar -xvf $(LEMON_NAME).tar.gz;	\
+	if [ -d $(LEMON_NAME)/ ]; then	\
+		cd $(LEMON_NAME)/ &&	\
+		mkdir build && cd build; \
+		sed '3d' ../CMakeLists.txt >> tmp; \
+		mv tmp ../CMakeLists.txt; \
+		cmake -DCMAKE_INSTALL_PREFIX=$(LOC_DIR)/lemon/ ..; \
+		make;	\
+		make install; \
+	else \
+		echo "Lemon library not found in the current directory" ; \
+		exit 1 ; \
+	fi
+
+.PHONY: clean-lemon
+clean-lemon:
+	@echo "* Cleaning lemon library..." ; \
+	rm -rf $(LEMON_NAME)/; \
+	rm -rf $(LOC_DIR)/lemon/
 
 .PHONY: snap
 snap: folders $(LOC_DIR)/include/snap-core/
